apps: Use actual icon name from app-info
flathub/backend pull request #17
Opened 2020-11-30 10:21 UTC by barthalion

Appstream is a gift that keeps on giving. appstream-compose sets the
icon name based on the value of <launchable> tag and not the name or ID
used by the referenced desktop file. The assumption that appid == icon
filename is wrong, even if happens to be true most of the time.

See https://github.com/flathub/flathub/pull/1949 for details.

2020-11-30 10:26 UTC, barthalion commented
Speaking of which, I'm not sure what I meant here:

https://github.com/flathub/backend/blob/master/app/apps.py#L36-L44

I assume it's actually dead code now.

2020-12-02 12:38 UTC, tchx84 commented
> Speaking of which, I'm not sure what I meant here:
> 
> https://github.com/flathub/backend/blob/master/app/apps.py#L36-L44
> 
> I assume it's actually dead code now.

For most part, yes, it does seem dead, except for 

```
            else:
                icon_path = icons["value"]
                return icon_path
```

Which I am not sure can still happen.

2020-12-02 12:38 UTC, tchx84 requested changes
This needs a rebase now.

2020-12-15 08:34 UTC, merged

2020-12-22 01:20 UTC, bilelmoussaoui commented
This change could have been the cause of a bunch of apps have their icons missing now? for example https://flathub.org/apps/details/com.github.utsushi.Utsushi & https://flathub.org/api/v1/apps/com.github.utsushi.Utsushi

2020-12-22 06:58 UTC, barthalion commented
Utsushi never had it working, the previous backend would not display it at all. Is there anything more in the bunch?

2020-12-22 10:13 UTC, bilelmoussaoui commented
Yes like https://flathub.org/apps/details/com.github.taiko2k.avvie or https://flathub.org/apps/details/com.anydesk.Anydesk

2020-12-22 11:09 UTC, barthalion commented
Yup, seems to be a regression for remote icons. I'll fix it.